import test from 'node:test';
import assert from 'node:assert/strict';
import {
  aggregateArenaScores,
  buildArenaCells,
  createArenaJudgePacket,
  runAnonymousArena
} from '../src/arena.js';
import { arenaComparisonPrompt } from '../src/prompts.js';
import { configuredArenaReviewers } from '../src/providers.js';

const TEST_PLAN = {
  tests: [{
    testId: 'portfolio_review',
    repeatCount: 2,
    input: { parts: [{ type: 'text', text: 'Review this supplied portfolio.' }] },
    constraints: ['Use only supplied holdings.'],
    expectedDeliverable: 'A concise risk review.'
  }]
};

const SUBMITTED_OUTPUTS = [
  { testId: 'portfolio_review', repeatIndex: 0, messageParts: [{ type: 'text', text: 'Response zero.' }] },
  { testId: 'portfolio_review', repeatIndex: 1, messageParts: [{ type: 'text', text: 'Response one.' }] }
];

const REPLICAS = [{
  runtimeId: 'cursor',
  validity: 'valid',
  outputs: [
    { testId: 'portfolio_review', repeatIndex: 0, messageParts: [{ type: 'text', text: 'Replica zero.' }] },
    { testId: 'portfolio_review', repeatIndex: 1, messageParts: [{ type: 'text', text: 'Replica one.' }] }
  ]
}, {
  runtimeId: 'broken-runtime',
  validity: 'invalid-infrastructure',
  outputs: []
}];

test('builds one shared-input arena cell per test and repeat for submitted and valid replicas', () => {
  const cells = buildArenaCells({
    testPlan: TEST_PLAN,
    submittedOutputs: SUBMITTED_OUTPUTS,
    replicas: REPLICAS
  });

  assert.equal(cells.length, 2);
  assert.deepEqual(cells.map((cell) => [cell.testId, cell.repeatIndex]), [
    ['portfolio_review', 0],
    ['portfolio_review', 1]
  ]);
  assert.deepEqual(cells[0].task, {
    input: TEST_PLAN.tests[0].input,
    constraints: TEST_PLAN.tests[0].constraints,
    expectedDeliverable: TEST_PLAN.tests[0].expectedDeliverable
  });
  assert.deepEqual(cells[0].candidates.map((candidate) => candidate.sourceId), [
    'submitted',
    'replica:cursor'
  ]);
});

test('creates a deterministic anonymous packet with independently shuffled candidate order', () => {
  const [cell] = buildArenaCells({
    testPlan: TEST_PLAN,
    submittedOutputs: SUBMITTED_OUTPUTS,
    replicas: REPLICAS
  });
  cell.candidates[0].output.messageParts[0].runtimeId = 'metadata-runtime-sentinel';
  cell.candidates[0].output.artifacts = [{
    artifactId: 'internal-artifact-sentinel',
    parts: [{ type: 'text', text: 'Useful artifact.' }],
    latencyMs: 44
  }];
  const reviewer = { id: 'gpt', name: 'OpenAI reviewer', model: 'hidden-model' };
  const first = createArenaJudgePacket(cell, reviewer, 123);
  const repeated = createArenaJudgePacket(cell, reviewer, 123);
  const secondJudge = createArenaJudgePacket(cell, { ...reviewer, id: 'claude' }, 456);

  assert.deepEqual(first, repeated);
  assert.match(first.candidates[0].candidateId, /^candidate-[a-f0-9]{8}$/u);
  assert.deepEqual(first.task, cell.task);
  assert.notEqual(
    JSON.stringify(first.candidates.map((candidate) => candidate.candidateId)),
    JSON.stringify(secondJudge.candidates.map((candidate) => candidate.candidateId))
  );
  for (const forbidden of [
    'submitted', 'cursor', 'OpenAI reviewer', 'hidden-model',
    'runtimeId', 'protocol', 'latency', 'a2a', 'reveal',
    'metadata-runtime-sentinel', 'internal-artifact-sentinel'
  ]) {
    assert.equal(JSON.stringify(first).toLowerCase().includes(forbidden.toLowerCase()), false, forbidden);
  }
});

test('removes identity-bearing artifact and Part metadata from packets and prompts', () => {
  const [cell] = buildArenaCells({
    testPlan: TEST_PLAN,
    submittedOutputs: SUBMITTED_OUTPUTS,
    replicas: REPLICAS
  });
  cell.candidates[0].output = {
    messageParts: [{
      type: 'text',
      text: 'Quality-relevant submitted result.',
      filename: 'submitted-agent-runtime-output.txt'
    }, {
      type: 'url',
      url: 'https://submitted-agent.example.internal/runtime/results.json',
      snapshot: {
        reference: 'snapshot_result',
        mediaType: 'application/json',
        byteLength: 99,
        sha256: 'a'.repeat(64)
      }
    }],
    artifacts: [{
      name: 'submitted-agent',
      description: 'Generated by the submitted agent runtime.',
      parts: [{
        type: 'raw',
        raw: { result: 'Useful content.' },
        filename: 'runtime-identity.json',
        mediaType: 'application/json'
      }]
    }]
  };

  const packet = createArenaJudgePacket(cell, { id: 'gpt' }, 123);
  const prompt = arenaComparisonPrompt(packet);

  assert.match(JSON.stringify(packet), /Quality-relevant submitted result/u);
  assert.match(prompt, /Quality-relevant submitted result/u);
  for (const forbidden of [
    'submitted-agent',
    'submitted-agent-runtime-output.txt',
    'runtime-identity.json',
    'submitted-agent.example.internal',
    'Generated by the submitted agent runtime'
  ]) {
    assert.equal(JSON.stringify(packet).includes(forbidden), false, `packet leaks ${forbidden}`);
    assert.equal(prompt.includes(forbidden), false, `prompt leaks ${forbidden}`);
  }
});

test('runs fresh judges, recalculates totals, and preserves anonymous and revealed score cubes separately', async () => {
  const vault = memoryVault();
  const result = await runAnonymousArena({
    testPlan: TEST_PLAN,
    submittedOutputs: SUBMITTED_OUTPUTS,
    replicas: REPLICAS,
    seed: 32,
    evidenceVault: vault,
    invokeJudge: async ({ packet }) => ({
      scores: packet.candidates.map((candidate, index) => ({
        candidateId: candidate.candidateId,
        dimensions: {
          taskConstraint: 80 + index,
          professionalQuality: 70,
          evidenceRisk: 60,
          artifactUsability: 50
        },
        total: 70,
        rationale: 'Compared only supplied results.',
        uncertainties: []
      }))
    })
  });

  assert.equal(result.arenaVersion, 'anonymous-arena/v1');
  assert.equal(result.cells.length, 8);
  assert.equal(result.scoringCube.length, 8);
  assert.equal(vault.records.length, 8);
  assert.deepEqual(Object.keys(result.scoringCube[0].scores).sort(), [
    'replica:cursor', 'submitted'
  ]);
  assert.equal(result.cells[0].anonymousScores[0].total, 70);
  assert.equal(JSON.stringify(result.cells).includes('replica:cursor'), false);
  assert.equal(JSON.stringify(result.cells).includes('submitted'), false);
  assert.equal(JSON.stringify(vault.records[0].payload).includes('replica:cursor'), true);
});

test('rejects reviewer overrides that do not match the frozen four-reviewer panel', async () => {
  const [cell] = buildArenaCells({
    testPlan: TEST_PLAN,
    submittedOutputs: SUBMITTED_OUTPUTS,
    replicas: REPLICAS
  });
  const reviewers = configuredArenaReviewers();

  await assert.rejects(runAnonymousArena({
    cells: [cell],
    reviewers: reviewers.slice(0, 3),
    allowTestReviewers: true,
    evidenceVault: memoryVault()
  }), /four|4|frozen|panel/iu);

  await assert.rejects(runAnonymousArena({
    cells: [cell],
    reviewers: reviewers.map((reviewer, index) => index === 0
      ? { ...reviewer, id: 'unapproved-reviewer' }
      : reviewer),
    allowTestReviewers: true,
    evidenceVault: memoryVault()
  }), /frozen|identity|panel/iu);
});

test('strips caller-supplied task metadata from judge packets', () => {
  const [cell] = buildArenaCells({
    testPlan: TEST_PLAN,
    submittedOutputs: SUBMITTED_OUTPUTS,
    replicas: REPLICAS
  });
  cell.task = {
    ...cell.task,
    agentId: 'submitted-agent',
    runtimeId: 'internal-runtime',
    absoluteResult: { passed: true },
    protocol: { version: 'A2A' },
    revealMap: { 'candidate-1': 'submitted' },
    latencyMs: 99,
    a2aStatus: 'completed',
    evidenceGrade: 'A',
    sourceId: 'submitted'
  };

  const packet = createArenaJudgePacket(cell, { id: 'gpt' }, 23);

  assert.deepEqual(packet.task, {
    input: TEST_PLAN.tests[0].input,
    constraints: TEST_PLAN.tests[0].constraints,
    expectedDeliverable: TEST_PLAN.tests[0].expectedDeliverable
  });
});

test('replaces identity-bearing snapshot references with opaque judge-local handles', () => {
  const [cell] = buildArenaCells({
    testPlan: TEST_PLAN,
    submittedOutputs: SUBMITTED_OUTPUTS,
    replicas: REPLICAS
  });
  cell.candidates[0].output.messageParts = [{
    type: 'url',
    url: 'https://files.example/submitted-runtime-report.json',
    snapshot: {
      reference: 'snapshot_submitted_agent',
      mediaType: 'application/json',
      byteLength: 512,
      sha256: 'b'.repeat(64)
    }
  }];

  const packet = createArenaJudgePacket(cell, { id: 'gpt' }, 77);
  const prompt = arenaComparisonPrompt(packet);
  const urlPart = packet.candidates
    .flatMap((candidate) => candidate.output.messageParts ?? [])
    .find((part) => part.type === 'url');

  assert.ok(urlPart);
  assert.equal(urlPart.snapshot.mediaType, 'application/json');
  assert.equal(urlPart.snapshot.byteLength, 512);
  assert.equal(urlPart.snapshot.sha256, 'b'.repeat(64));
  assert.match(urlPart.snapshot.reference, /^snapshot_[a-f0-9]{8}$/u);
  for (const forbidden of [
    'snapshot_submitted_agent',
    'submitted',
    'runtime',
    'agent'
  ]) {
    assert.equal(JSON.stringify(packet).includes(forbidden), false, `packet leaks ${forbidden}`);
    assert.equal(prompt.includes(forbidden), false, `prompt leaks ${forbidden}`);
  }
});

test('rejects URL snapshots with metadata outside the locked shape', () => {
  const [cell] = buildArenaCells({
    testPlan: TEST_PLAN,
    submittedOutputs: SUBMITTED_OUTPUTS,
    replicas: REPLICAS
  });
  cell.candidates[0].output.messageParts = [{
    type: 'url',
    url: 'https://files.example/report.csv',
    snapshot: {
      reference: 'snapshot_report',
      mediaType: 'text/csv',
      byteLength: 128,
      sha256: 'a'.repeat(64),
      runtimeId: 'internal-runtime',
      latencyMs: 99,
      sourceId: 'submitted',
      revealMap: { 'candidate-1': 'submitted' }
    }
  }];

  const packet = createArenaJudgePacket(cell, { id: 'gpt' }, 24);
  const urlPart = packet.candidates
    .flatMap((candidate) => candidate.output.messageParts ?? [])
    .find((part) => part.type === 'url');

  assert.equal(urlPart, undefined);
});

test('rejects malformed judge payloads and retains only valid replica score keys', async () => {
  const judgement = {
    testId: 'portfolio_review',
    repeatIndex: 0,
    judgeId: 'gpt',
    scores: {
      submitted: 75,
      'replica:cursor': 70,
      'replica:invalid': 99
    }
  };
  assert.deepEqual(aggregateArenaScores([judgement], ['cursor']), [{
    testId: 'portfolio_review',
    repeatIndex: 0,
    judgeId: 'gpt',
    scores: { submitted: 75, 'replica:cursor': 70 }
  }]);

  const [cell] = buildArenaCells({
    testPlan: TEST_PLAN,
    submittedOutputs: SUBMITTED_OUTPUTS,
    replicas: REPLICAS
  });
  const packet = createArenaJudgePacket(cell, { id: 'gpt' }, 12);
  await assert.rejects(runAnonymousArena({
    cells: [cell],
    evidenceVault: memoryVault(),
    invokeJudge: async () => ({
      scores: [{
        candidateId: packet.candidates[0].candidateId,
        dimensions: {
          taskConstraint: 101,
          professionalQuality: 1,
          evidenceRisk: 1,
          artifactUsability: 1
        },
        total: 1,
        rationale: 'bad',
        uncertainties: []
      }]
    })
  }), /candidate|0–100|range/iu);
});

test('rejects finite judge totals outside the score range', async () => {
  const [cell] = buildArenaCells({
    testPlan: TEST_PLAN,
    submittedOutputs: SUBMITTED_OUTPUTS,
    replicas: REPLICAS
  });

  for (const total of [-1, 101]) {
    await assert.rejects(runAnonymousArena({
      cells: [cell],
      evidenceVault: memoryVault(),
      invokeJudge: async ({ packet }) => ({
        scores: packet.candidates.map((candidate) => ({
          candidateId: candidate.candidateId,
          dimensions: {
            taskConstraint: 80,
            professionalQuality: 70,
            evidenceRisk: 60,
            artifactUsability: 50
          },
          total,
          rationale: 'bad total',
          uncertainties: []
        }))
      })
    }), /total|0–100|range/iu);
  }
});

function memoryVault() {
  return {
    records: [],
    async put(record) {
      this.records.push(record);
      return record;
    }
  };
}
